# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBWebView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
  # Pods for HBWebView

end
